config/routes.rb
Rails.application.routes.draw do
  resources :tracks
  resources :hikes

  root 'hikes#index'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/signup' => 'users#new'
  post '/users' => 'users#create'

end

app/models/hike.rb
class Hike < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  has_many :tracks, :dependent => :destroy
  has_many :tracksegments, :through => :tracks
end

app/models/point.rb
class Point < ActiveRecord::Base
  belongs_to :tracksegment
  attr_accessor :description, :elevation, :latitude, :longitude, :name, :point_created_at
end

app/models/track.rb
class Track < ActiveRecord::Base
  attr_accessor :name, :gpx
  belongs_to :hike
  has_many :tracksegments, :dependent => :destroy
  has_many :points, :through => :tracksegments

  has_attached_file :gpx

  before_save :parse_file

  def parse_file
    tempfile = gpx.queued_for_write[:original]
    doc = Nokogiri::XML(tempfile)
    parse_xml(doc)
  end

  def parse_xml(doc)
    doc.root.elements.each do |node|
      parse_tracks(node)
    end
  end

  def parse_tracks(node)
    if node.node_name.eql? 'trk'
      node.elements.each do |node|
        parse_track_segments(node)
      end
    end
  end

  def parse_track_segments(node)
    if node.node_name.eql? 'trkseg'
      tmp_segment = Tracksegment.new
      node.elements.each do |node|
        parse_points(node, tmp_segment)
      end
      self.tracksegments << tmp_segment
    end
  end

  def parse_points(node,tmp_segment)
    if node.node_name.eql? 'trkpt'
      tmp_point = Point.new
      tmp_point.latitude = node.attr("lat")
      tmp_point.longitude = node.attr("lon")
      node.elements.each do |node|
        tmp_point.name = node.text.to_s if node.name.eql? 'name'
        tmp_point.elevation = node.text.to_s if node.name.eql? 'ele'
        tmp_point.description = node.text.to_s if node.name.eql? 'desc'
        tmp_point.point_created_at = node.text.to_s if node.name.eql? 'time'
      end
      tmp_segment.points << tmp_point
    end
  end

end

app/models/tracksegment.rb
class Tracksegment < ActiveRecord::Base
  belongs_to :track
  has_many :points, :dependent => :destroy
  # attr_accessible :title, :body
end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end
end

app/controllers/hikes_controller.rb
class HikesController < ApplicationController

  before_filter :authorize
  before_action :set_hike, only: [:show, :edit, :update, :destroy]

  # GET /hikes
  # GET /hikes.json
  def index
    @hikes = Hike.all
  end

  # GET /hikes/1
  # GET /hikes/1.json
  def show
  end

  # GET /hikes/new
  def new
    @hike = Hike.new
  end

  # GET /hikes/1/edit
  def edit
  end

  # POST /hikes
  # POST /hikes.json
  def create
    @hike = Hike.new(hike_params)

    respond_to do |format|
      if @hike.save
        format.html { redirect_to @hike, notice: 'Hike was successfully created. Happy trails!' }
        format.json { render :show, status: :created, location: @hike }
      else
        format.html { render :new }
        format.json { render json: @hike.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hikes/1
  # PATCH/PUT /hikes/1.json
  def update
    respond_to do |format|
      if @hike.update(hike_params)
        format.html { redirect_to @hike, notice: 'Hike was successfully updated. Get back out there!' }
        format.json { render :show, status: :ok, location: @hike }
      else
        format.html { render :edit }
        format.json { render json: @hike.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hikes/1
  # DELETE /hikes/1.json
  def destroy
    @hike.destroy
    respond_to do |format|
      format.html { redirect_to hikes_url, notice: 'Hike was successfully destroyed. Mother Nature is sad.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hike
      @hike = Hike.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hike_params
      params.require(:hike).permit(:title, :distance, :difficulty, :region, :description, :image, :link, :completed)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    # If the user exists AND the password entered is correct.
    if user && user.authenticate(params[:password])
      # Save the user id inside the browser cookie. This is how we keep the user
      # logged in when they navigate around our website.
      session[:user_id] = user.id
      redirect_to '/'
    else
    # If user's login doesn't work, send them back to the login form.
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end

end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :set_track, only: [:show, :edit, :update, :destroy]

  # GET /tracks
  # GET /tracks.json
  def index
    @tracks = Track.all
  end

  # GET /tracks/1
  # GET /tracks/1.json
  def show
  end

  # GET /tracks/new
  def new
    @track = Track.new
  end

  # GET /tracks/1/edit
  def edit
  end

  # POST /tracks
  # POST /tracks.json
  def create
    @track = Track.new(track_params)

    respond_to do |format|
      if @track.save
        format.html { redirect_to @track, notice: 'Track was successfully created.' }
        format.json { render :show, status: :created, location: @track }
      else
        format.html { render :new }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tracks/1
  # PATCH/PUT /tracks/1.json
  def update
    respond_to do |format|
      if @track.update(track_params)
        format.html { redirect_to @track, notice: 'Track was successfully updated.' }
        format.json { render :show, status: :ok, location: @track }
      else
        format.html { render :edit }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tracks/1
  # DELETE /tracks/1.json
  def destroy
    @track.destroy
    respond_to do |format|
      format.html { redirect_to tracks_url, notice: 'Track was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_track
      @track = Track.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def track_params
      params.require(:track).permit(:hike_id, :name, :gpx)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hikes_helper.rb
module HikesHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/hikes/_form.html.erb
<%= form_for @hike, html: { multipart: true } do |f| %>
  <% if @hike.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hike.errors.count, "error") %> prohibited this hike from being saved:</h2>

      <ul>
      <% @hike.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :distance %><br>
    <%= f.number_field :distance %>
  </div>
  <div class="field">
    <%= f.label :difficulty %><br>
    <%= f.text_field :difficulty %>
  </div>
  <div class="field">
    <%= f.label :region %><br>
    <%= f.text_field :region %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :completed %><br>
    <%= f.check_box :completed %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hikes/edit.html.erb
<h1>Editing Hike</h1>

<%= render 'form' %>

<%= link_to 'Show', @hike %> |
<%= link_to 'Back', hikes_path %>

app/views/hikes/index.html.erb
<!DOCTYPE html>
<html lang = "en-US">
 <head>
 <meta charset = "UTF-8">
  <link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
  <link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
  <link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
  <link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
  <link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
  <link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
  <link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
  <link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
  <link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
  <link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
  <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
  <link rel="manifest" href="/manifest.json">
  <meta name="msapplication-TileColor" content="#ffffff">
  <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
  <meta name="theme-color" content="#ffffff">
 <title>externalStyle.html</title>
 <link rel = "stylesheet"
   type = "text/css"
   href = "hikes.css" />
 </head>
 <body>
  <p id="notice"><%= notice %></p>
  <ul class="nav nav-tabs" role="tablist">
    <li class="active"><%= link_to 'View hike', hikes_path %></li>
    <li><%= link_to 'New hike', new_hike_path %></li>
  </ul>
  <div id="hike_list">
    <h1>Hikes in Georgia</h1>

    <table class="table-responsive">
    <% @hikes.each do |hike| %>
      <!-- <tr class="<%= cycle('list_line_odd', 'list_line_even') %>"> -->
      <tr>
        <td>
          <%= image_tag(hike.image, :class => 'list_image') %>
        </td>

        <td class= "list_description">
          <dl>
            <dt><a href="/hikes/<%= hike.id %>"><%= hike.title %></a></dt>
            <dd><%= truncate(strip_tags(hike.description), :length => 400) %></dd>
          </dl>
        </td>
      </tr>
      <tr>
        <td class= "link_title" align="right"></td>
        <td class="list_link">
          <a href="<%= hike.link %>" target="_blank"><%= hike.link %></a>
        </td>
      </tr>
      <tr>
        <td></td>
        <td class="list_actions">
          <%= link_to 'Show', hike, class: 'btn btn-primary btn-xs' %>
          <%= link_to 'Edit', edit_hike_path(hike), class: 'btn btn-info btn-xs' %>
          <%= link_to 'Destroy', hike,
                      :confirm => 'Are you sure?',
                      :method => :delete,
                      class: 'btn btn-danger btn-xs' %>
        </td>
      </tr>
    <% end %>
    </table>
  </div>

  <br />

  <%= link_to new_hike_path, class: 'btn btn-success' do %>
    <i class="glyphicon glyphicon-plus"></i> New hike
  <% end %>
</body>
</html>

<!-- <p id="notice"><%= notice %></p>

<h1>Listing Hikes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Distance</th>
      <th>Difficulty</th>
      <th>Region</th>
      <th>Description</th>
      <th>Image</th>
      <th>Link</th>
      <th>Completed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hikes.each do |hike| %>
      <tr>
        <td><%= hike.title %></td>
        <td><%= hike.distance %></td>
        <td><%= hike.difficulty %></td>
        <td><%= hike.region %></td>
        <td><%= hike.description %></td>
        <td><%= hike.image %></td>
        <td><%= hike.link %></td>
        <td><%= hike.completed %></td>
        <td><%= link_to 'Show', hike %></td>
        <td><%= link_to 'Edit', edit_hike_path(hike) %></td>
        <td><%= link_to 'Destroy', hike, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hike', new_hike_path %>
 -->

app/views/hikes/new.html.erb
<ul class="nav nav-tabs" role="tablist">
  <li><%= link_to 'View hike', hikes_path %></li>
  <li class="active"><%= link_to 'New hike', new_hike_path %></li>
</ul>


<h1>New Hike</h1>

<%= render 'form' %>

<%= link_to 'Back', hikes_path %>

app/views/hikes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @hike.title %>
</p>

<p>
  <strong>Distance:</strong>
  <%= @hike.distance %> km
</p>

<p>
  <strong>Difficulty:</strong>
  <%= @hike.difficulty %>
</p>

<p>
  <strong>Region:</strong>
  <%= @hike.region %>
</p>

<p>
  <strong>Description:</strong>
  <%= @hike.description %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @hike.image_url.to_s, alt: "Image", class: "img-responsive" %>
</p>

<p>
  <strong>Link:</strong>
  <a href="<%= @hike.link %>" target="_blank"><%= @hike.link %></a>
</p>

<p>
  <strong>Completed:</strong>
  <%= @hike.completed %>
</p>

<%= link_to 'Edit', edit_hike_path(@hike) %> |
<%= link_to 'Back', hikes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GHikes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if current_user %>
    Signed in as <%= current_user.name %> | <%= link_to "Logout", '/logout' %>
  <% else %>
    <!-- <%= link_to 'Login', '/login' %> -->
    <%= link_to 'Login', '/login' %> | <%= link_to 'Signup', '/signup' %>
  <% end %>
  <%= render 'shared/navigation' %>
<div id="main-container" class="container">
  <div class="row">
    <div class="col-xs-3">
      <h3>About gHikes</h3>
      <img src="/images/1220.jpg" width="100%">
      <p>gHikes is a side project of Nathan Anderson of
      <a href="http://www.openroadbeforeme.com" ref="_blank">The Open Road Before Me</a>
      and is an effort to catalogue treks and hikes throughout the country of Georgia</p>
    </div>
    <div class="col-xs-9">
      <%= yield %>
    </div>
  </div>
</div>

</body>
</html>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">gHikes</a>
    </div>
  </div>
</nav>

app/views/tracks/_form.html.erb
<%= form_for @track, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :gpx, :class => 'control-label' %>
    <div class="controls">
      <%= f.file_field :gpx %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                tracks_path, :class => 'btn' %>
  </div>
<% end %>

app/views/tracks/edit.html.erb
<h1>Editing Track</h1>

<%= render 'form' %>

<%= link_to 'Show', @track %> |
<%= link_to 'Back', tracks_path %>

app/views/tracks/index.html.erb
<!DOCTYPE html>
<html lang = "en-US">
  <head>
    <meta charset = "UTF-8">

    <title>externalStyle.html</title>
    <link rel = "stylesheet"
    type = "text/css"
    href = "hikes.css" />
  </head>
 <p id="notice"><%= notice %></p>
<body>
 <ul class="nav nav-tabs" role="tablist">
   <li class="active"><%= link_to 'View track', tracks_path %></li>
   <li><%= link_to 'New track', new_track_path %></li>
 </ul>
<h1>Listing Tracks</h1>

<table>
  <thead>
    <tr>
      <th>Hike</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tracks.each do |track| %>
      <tr>
        <td><%= track.hike %></td>
        <td><%= track.name %></td>
        <td><%= link_to 'Show', track %></td>
        <td><%= link_to 'Edit', edit_track_path(track) %></td>
        <td><%= link_to 'Destroy', track, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Track', new_track_path %>

app/views/tracks/new.html.erb
<!DOCTYPE html>
<html lang = "en-US">
  <head>
    <meta charset = "UTF-8">

    <title>externalStyle.html</title>
    <link rel = "stylesheet"
    type = "text/css"
    href = "hikes.css" />
  </head>
 <p id="notice"><%= notice %></p>
<body>
  <ul class="nav nav-tabs" role="tablist">
    <li><%= link_to 'View track', tracks_path %></li>
    <li class="active"><%= link_to 'New track', new_track_path %></li>
  </ul>
<h1>New Track</h1>

<%= render 'form' %>

<%= link_to 'Back', tracks_path %>

app/views/tracks/show.html.erb
<!-- <p id="notice"><%= notice %></p>

<p>
  <strong>Hike:</strong>
  <%= @track.hike %>
</p>

<p>
  <strong>Name:</strong>
  <%= @track.name %>
</p>

<%= link_to 'Edit', edit_track_path(@track) %> |
<%= link_to 'Back', tracks_path %> -->
<%- model_class = Track -%>
  <div class="page-header">
    <h1><%=t '.title', :default => model_class.model_name.human %></h1>
  </div>

  <dl class="dl-horizontal">
    <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
    <dd><%= @track.name %></dd>
    <dt><strong><%= model_class.human_attribute_name(:gpx_file_name) %>:</strong></dt>
    <dd><%= @track.gpx_file_name %></dd>
    <dt><strong><%= model_class.human_attribute_name(:gpx_content_type) %>:</strong></dt>
    <dd><%= @track.gpx_content_type %></dd>
    <dt><strong><%= model_class.human_attribute_name(:gpx_file_size) %>:</strong></dt>
    <dd><%= @track.gpx_file_size %></dd>
    <dt><strong><%= model_class.human_attribute_name(:gpx_updated_at) %>:</strong></dt>
    <dd><%= @track.gpx_updated_at %></dd>
  </dl>

  <div class="form-actions">
    <%= link_to t('.back', :default => t("helpers.links.back")),
                tracks_path, :class => 'btn'  %>
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_track_path(@track), :class => 'btn' %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                track_path(@track),
                :method => 'delete',
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-danger' %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>ID</th>
        <th>Point No.</th>
        <th>Latitude</th>
        <th>Longitude</th>
        <th>Elevation</th>
        <th>Description</th>
        <th>Time</th>
      </tr>
    </thead>
    <tbody>
      <% @track.points.each do |point| %>
        <tr>
          <td><%= point.id %></td>
          <td><%= point.name %></td>
          <td><%= point.latitude %></td>
          <td><%= point.longitude %></td>
          <td><%= point.elevation %></td>
          <td><%= point.description %></td>
          <td><%= point.point_created_at %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="form-actions">
    <%= link_to t('.back', :default => t("helpers.links.back")),
                tracks_path, :class => 'btn'  %>
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_track_path(@track), :class => 'btn' %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                track_path(@track),
                :method => 'delete',
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-danger' %>
  </div>

app/views/users/new.html.erb
<h1>Signup!</h1>

<table class="table" max-width="35%">
<%= form_for :user, url: '/users' do |f| %>
  <tr>
    <td>Name: </td><td><%= f.text_field :name %></td>
  </tr>
  <tr>
    <td>Email: </td><td><%= f.text_field :email %></td>
  </tr>
  <tr>
    <td>Password: </td><td><%= f.password_field :password %></td>
  </tr>
  <tr>
    <td>Password Confirmation: </td><td><%= f.password_field :password_confirmation %></td>
  </tr>
  <tr>
    <td></td><td><%= f.submit "Submit" %></td>
  </tr>
<% end %>
</table>